language: node_js
node_js:
  - "9"
dist: trusty
sudo: false
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

branches:
  only:
  - master
install:
  - npm install
script:
  - npm run test --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox